### ISSUE TITLE
Analysis Mode 0-8

### ISSUE THREAD

**Issue by hero2017** [Zerbinati/Sugar_Galaxy#88]
I tried to find an explanation of this option but couldn't. Can someone tell me how this works?

What does it mean if it's set to 0 or 8? Do I need to change this from 0 to some other number to make use of Contempt when I'm analysing a single position infinitely until I stop the engine or if I'm making engine moves back and forth? Does it have anything to do with Contempt or am I explaining it for the wrong option, and instead should be for the UCI_AnalyseMode option?

**Comment by MichaelB7** [comment]
It turns multiPV on , but still only gives you the best line.  Using MultiPV will miss fewer tactical shots but at a cost of some ELO. Highly recommended for CC play. 
Code snippet :
if (tactical) multiPV = size_t(pow(2, tactical));

So tactical set to zero is equal to multiPV set to 1 , which is the default.  It then doubles from that point on so that tactical 8 is the same as using multiPV 256.  I have had it in my fork of Stockfish for a while “McBrain” , but here it is call “Analysis” in the uci  option , but tactical in the code.  I called it tactical in both places.  I have absolutely no problem with anyone using any McBrain code, after all that’s the whole point of open source and I use code from other forks as well.   With that said , Sugar , by far has more original non Stockfish code than any other SF fork , thus making it one of my favorites. Always play out the best candidate moves when using an engine to analyze , moving pieces back and forth. There is so much pruning being today , that engines are not always seeing the best move. I would recommend a setting anywhere from 1 to 4 - higher than 4 and the width of the search is getting too wide.

**Comment by hero2017** [comment]
Cool, thanks. I presume it'll take much longer to reach certain depths the higher the number specified for analysis mode.

Also just to clarify, we're talking about the UCI option Analysis Mode [0-8] only which does/doesn't require the other UCI option enabled called UCI_AnalyseMode? The two options sound almost identical so perhaps it should be renamed to Tactical as well for Sugar.

**Comment by MichaelB7** [comment]
Correct - independent of the similar sounding option, also correct higher depths will take longer to reach , thus the Elo lost.
